name: 'Deployment: Production'

on:
  push: 
    branches: [current-release]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      github-environment: Production