name: 'Deployment: Staging'

on:
  pull_request: 
    branches: [release]
    types: [ready_for_review, synchronize, opened, reopened]

jobs:
  staging:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      github-environment: Staging