name: Release Tags

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - run: gh pr create --base current-release --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}