name: Create Release Pull Request

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - run: git checkout -B release-${{ github.event.release.tag_name }}

      - run: git push -u origin release-${{ github.event.release.tag_name }}
      
      - run: gh pr create --base release --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}